id: I4AAF4D52
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:33:24+00:00'
last_modified: '2022-06-07T22:21:35.862794+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21829
  title: ལུས་ཁམས་བདེ་ཐང་སྐོར་གྱི་ཤེས་བྱ ༦༦
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6F16:
      image_group_id: I1KG21926
      title: ''
      total_pages: 274
      order: 1
      base_file: 6F16.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
