id: P004369
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:15:46.447000
source_metadata:
  id: bdr:W1KG21829
  title: ལུས་ཁམས་བདེ་ཐང་སྐོར་གྱི་ཤེས་བྱ ༦༦
  author: ''
  volumes:
    8d00d48be3424679b1fe6b444748e634:
      image_group_id: I1KG21926
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
